# OPTIMIZED Credit Risk AI Platform Configuration
# Version: 2.0 - Performance Enhanced

# Enhanced Model Configuration
model:
  path: "artifacts/model_data.joblib"
  version: "2.0.0"
  type: "logistic_regression_optimized"
  features_count: 13
  algorithm: "LogisticRegression"
  training_method: "SMOTE-Tomek + Optuna"
  
  # OPTIMIZATION: Enhanced validation settings
  validation:
    enable_health_checks: true
    health_check_interval_hours: 6  # More frequent checks
    prediction_timeout_seconds: 10  # Reduced timeout
    max_batch_size: 5000  # Increased for better throughput
    enable_confidence_intervals: true
    
  # OPTIMIZATION: Performance monitoring thresholds  
  performance_thresholds:
    max_prediction_time_seconds: 1.0  # Stricter requirement
    min_auc: 0.75  # Slightly higher bar
    min_gini: 0.50  # Enhanced requirement
    min_ks: 45.0   # Better discrimination
    max_psi: 0.20  # Tighter stability
    min_precision: 0.50
    min_recall: 0.90
    
  # OPTIMIZATION: Caching configuration
  caching:
    enable_model_cache: true
    cache_ttl_seconds: 3600  # 1 hour
    enable_prediction_cache: false  # Don't cache predictions
    enable_feature_cache: true
    max_cache_size_mb: 256

# Enhanced Scoring Configuration  
scoring:
  base_score: 300
  max_score: 900
  scale_length: 600
  confidence_bands: true  # NEW: Enable confidence intervals
  
  # Enhanced rating thresholds with more granular levels
  rating_thresholds:
    exceptional: 850
    excellent: 750
    good: 650
    average: 500
    poor: 400
    very_poor: 300
    
  # OPTIMIZATION: Dynamic risk-based pricing
  interest_rate_adjustments:
    exceptional: -1.0  # Better rates for excellent customers
    excellent: -0.5
    good: 0.0
    average: 1.0
    poor: 2.5
    very_poor: 4.0
    
  # NEW: Score band calculations
  score_bands:
    enable: true
    band_width: 25  # +/- 25 points
    confidence_level: 0.95

# Enhanced Risk Configuration
risk:
  # OPTIMIZATION: Dynamic thresholds based on portfolio performance
  approval_threshold: 0.08  # Slightly more conservative
  review_threshold: 0.18
  reject_threshold: 0.32
  
  # NEW: Time-based threshold adjustments
  threshold_adjustments:
    enable_dynamic: true
    adjustment_frequency_days: 30
    max_adjustment_percent: 15
    
  # Enhanced risk indicators with more metrics
  high_risk_indicators:
    credit_utilization: 75
    loan_to_income: 4.0  # More conservative
    delinquency_ratio: 25
    avg_dpd: 25  # Stricter requirement
    debt_burden_ratio: 55
    
  # OPTIMIZATION: Enhanced risk categories
  risk_categories:
    very_low: 0.02
    low: 0.05
    moderate: 0.10
    high: 0.18
    very_high: 0.32
    extreme: 1.0
    
  # NEW: Risk score calibration
  calibration:
    enable: true
    recalibrate_frequency_days: 90
    min_calibration_samples: 1000

# OPTIMIZATION: Enhanced Business Rules
business_rules:
  # Stricter validation rules
  age:
    min: 18
    max: 70
    warning_min: 22  # Slightly higher
    warning_max: 62  # More conservative
    
  income:
    min: 150000  # Increased minimum
    warning_min: 400000  # Higher warning threshold
    max: 100000000  # 10 Crores (increased)
    currency: "INR"
    
  loan_amount:
    min: 75000  # Increased minimum
    max: 15000000  # 1.5 Crores (increased)
    warning_max: 7500000  # 75 Lakhs
    currency: "INR"
    
  loan_tenure:
    min_months: 6
    max_months: 300  # 25 years (reduced)
    warning_max_months: 240  # 20 years
    optimal_max_months: 180  # 15 years
    
  # OPTIMIZATION: Enhanced ratio validations
  loan_to_income:
    max_ratio: 8  # More conservative
    warning_ratio: 4
    regulatory_limit: 8
    optimal_ratio: 3
    
  debt_burden:
    max_ratio: 0.55  # More conservative
    warning_ratio: 0.45
    optimal_ratio: 0.35
    
  credit_utilization:
    max_ratio: 100
    high_threshold: 65  # Lower threshold
    very_high_threshold: 85
    optimal_threshold: 30
    
  # OPTIMIZATION: Enhanced delinquency rules
  delinquency:
    max_ratio: 100
    high_threshold: 20  # Lower threshold
    very_high_threshold: 40
    max_avg_dpd: 150  # Stricter
    high_avg_dpd: 25  # Lower threshold
    very_high_avg_dpd: 75
    
  # NEW: Processing fee validation
  processing_fee:
    max_percentage: 0.025  # 2.5% (reduced)
    standard_percentage: 0.015
    warning_percentage: 0.02

# OPTIMIZATION: Enhanced Feature Engineering
features:
  continuous:
    - age
    - income
    - loan_amount
    - loan_tenure_months
    - credit_utilization_ratio
    - delinquency_ratio
    - avg_dpd_per_delinquency
    - loan_to_income
    
  categorical:
    - residence_type
    - loan_purpose
    - loan_type
    - employment_status
    
  engineered:
    - loan_to_income
    - delinquency_ratio
    - avg_dpd_per_delinquency
    - debt_burden_ratio
    
  # OPTIMIZATION: Enhanced feature validation
  validation:
    enable_range_checks: true
    enable_outlier_detection: true
    max_loan_to_income: 15  # Increased range
    max_delinquency_ratio: 100
    max_avg_dpd: 365
    outlier_threshold_std: 3
    
  # OPTIMIZATION: Cached training defaults
  training_defaults:
    number_of_dependants: 1.2
    years_at_current_address: 6.8
    zipcode: 400601
    number_of_closed_accounts: 1.8
    enquiry_count: 3.2
    bank_balance_multiplier: 0.08  # 8% of annual income

# OPTIMIZATION: Enhanced Performance Monitoring
performance_monitoring:
  enable: true
  
  # Real-time metrics
  real_time:
    track_prediction_time: true
    track_error_rates: true
    track_memory_usage: true
    track_cache_hit_rates: true
    
  # Performance benchmarks
  benchmarks:
    target_prediction_time_seconds: 0.3
    max_acceptable_time_seconds: 1.0
    target_throughput_per_second: 100
    max_memory_usage_mb: 512
    min_cache_hit_rate: 0.8
    
  # Alerting thresholds
  alerts:
    slow_prediction_threshold: 2.0
    high_error_rate_threshold: 0.05
    memory_warning_threshold: 400
    memory_critical_threshold: 480

# OPTIMIZATION: Enhanced Batch Processing
batch:
  # Improved batch settings
  max_records: 10000
  chunk_size: 200  # Optimized chunk size
  parallel_workers: 8  # Increased workers
  timeout_seconds: 600  # Increased timeout
  
  # OPTIMIZATION: Memory management
  memory_management:
    enable: true
    max_memory_per_batch_mb: 1024
    garbage_collection_frequency: 100
    
  # Enhanced validation
  validation:
    enable_row_validation: true
    stop_on_critical_errors: true
    max_error_rate: 0.05  # Stricter
    enable_data_quality_checks: true
    
  # Performance optimization
  processing:
    enable_parallel: true
    enable_vectorization: true
    memory_limit_mb: 2048
    temp_storage_path: "temp/"
    cleanup_temp_files: true

# OPTIMIZATION: Enhanced UI Configuration
ui:
  theme: "light"
  primary_color: "#667eea"
  secondary_color: "#764ba2"
  accent_color: "#f093fb"
  
  # Performance settings
  chart_settings:
    height: 400
    width: "auto"
    animation_duration: 300
    enable_lazy_loading: true
    
  table_settings:
    page_size: 25  # Increased page size
    show_index: false
    enable_sorting: true
    enable_filtering: true
    
  # OPTIMIZATION: Real-time features
  real_time:
    enable_validation: true
    validation_debounce_ms: 300
    show_warnings: true
    highlight_errors: true
    enable_auto_save: false
    
  # Enhanced display settings
  display:
    currency_format: "indian"
    number_precision: 3  # Increased precision
    percentage_precision: 1
    show_debug_info: false
    enable_tooltips: true
    
  # NEW: Accessibility features
  accessibility:
    enable_high_contrast: false
    enable_large_fonts: false
    enable_screen_reader: true
    keyboard_navigation: true

# OPTIMIZATION: Enhanced Monitoring & Alerting
monitoring:
  enable_logging: true
  log_level: "INFO"
  log_path: "logs/app.log"
  log_rotation: true
  max_log_size_mb: 100
  
  # OPTIMIZATION: Enhanced health monitoring
  health_checks:
    enable: true
    interval_minutes: 30  # More frequent
    alert_on_failure: true
    max_consecutive_failures: 2  # Lower tolerance
    detailed_logging: true
    
  # OPTIMIZATION: Performance monitoring
  performance:
    track_prediction_time: true
    track_error_rates: true
    track_cache_performance: true
    alert_slow_predictions: true
    max_prediction_time_seconds: 1.0
    enable_profiling: false
  
  # Enhanced alerting system
  alerts:
    channels:
      - email
      - webhook
      - log
    
    thresholds:
      high_risk_threshold: 0.25
      low_approval_rate: 0.15
      model_degradation: 0.03
      system_error_rate: 0.02
      memory_usage_threshold: 0.8
      
    escalation:
      level_1_threshold_minutes: 5
      level_2_threshold_minutes: 15
      level_3_threshold_minutes: 60
      max_level: 3
      enable_auto_escalation: true

# OPTIMIZATION: Enhanced Audit Configuration
audit:
  enable: true
  log_all_predictions: true
  log_user_actions: true
  log_system_events: true
  retention_days: 730  # 2 years
  
  # Comprehensive audit fields
  fields_to_log:
    - user_id
    - session_id
    - application_id
    - timestamp
    - action
    - input_data_hash  # Hash instead of full data
    - prediction_result
    - processing_time
    - model_version
    - ip_address
    - user_agent
    
  # Enhanced export capabilities
  export:
    enable: true
    formats: ["json", "csv", "parquet"]
    compression: true
    encryption: false
    schedule_daily_backup: true

# OPTIMIZATION: Enhanced Security
security:
  enable_encryption: true
  session_timeout_minutes: 240  # 4 hours
  max_file_size_mb: 25  # Increased limit
  
  # File validation
  allowed_file_types:
    - csv
    - xlsx
    - xls
    - json
    
  # Enhanced input validation
  input_validation:
    enable_sql_injection_check: true
    enable_xss_protection: true
    enable_csrf_protection: true
    max_input_length: 2000  # Increased
    enable_rate_limiting: true
    
  # Privacy protection
  privacy:
    mask_sensitive_data: true
    log_data_access: true
    enable_data_retention_policy: true
    anonymize_logs: true
    gdpr_compliance: true

# OPTIMIZATION: Enhanced Reporting
reports:
  enable_pdf: true
  enable_excel: true
  enable_interactive: true
  template_path: "templates/"
  output_path: "reports/"
  
  # Comprehensive report sections
  sections:
    - executive_summary
    - risk_assessment
    - financial_analysis
    - model_performance
    - recommendations
    - compliance_check
    - audit_trail
    - appendices
    
  # Enhanced formatting
  formatting:
    include_charts: true
    include_model_diagnostics: true
    include_confidence_intervals: true
    include_sensitivity_analysis: true
    high_quality_images: true
    
  # OPTIMIZATION: Automated reporting
  automation:
    enable_scheduled_reports: true
    daily_summary: true
    weekly_portfolio_review: true
    monthly_model_performance: true
    quarterly_compliance_report: true

# OPTIMIZATION: Enhanced Model Governance
governance:
  model_validation:
    enable: true
    frequency_days: 60  # More frequent
    back_testing_enabled: true
    stress_testing_enabled: true
    
  compliance:
    regulatory_framework: "RBI_Guidelines_2024"
    documentation_required: true
    approval_workflow: true  # Enabled for production
    model_risk_rating: "Medium"
    
  version_control:
    track_model_versions: true
    require_approval_for_changes: true
    backup_previous_versions: true
    max_versions_to_keep: 5
    
  # NEW: Model lifecycle management
  lifecycle:
    development_stage: "Production"
    deployment_date: "2024-01-15"
    next_review_date: "2024-04-15"
    retirement_criteria: "AUC < 0.75 for 2 consecutive months"

# OPTIMIZATION: Enhanced Data Quality
data_quality:
  validation:
    enable: true
    check_missing_values: true
    check_outliers: true
    check_data_types: true
    check_business_rules: true
    check_referential_integrity: true
    
  cleansing:
    auto_fix_data_types: true
    handle_missing_values: "mode"
    outlier_treatment: "cap"
    enable_data_standardization: true
    
  monitoring:
    track_data_drift: true
    alert_on_anomalies: true
    data_quality_threshold: 0.97  # Higher standard
    drift_detection_window_days: 30
    
  # NEW: Data profiling
  profiling:
    enable: true
    profile_frequency_days: 7
    track_distributions: true
    track_correlations: true

# OPTIMIZATION: Enhanced Environment Configuration
environment:
  name: "production"  # Changed from development
  debug_mode: false  # Disabled for production
  enable_profiling: true  # Enabled for monitoring
  
  # Resource optimization
  resources:
    max_memory_usage_mb: 8192  # Increased
    max_cpu_usage_percent: 70  # More conservative
    enable_memory_monitoring: true
    enable_cpu_monitoring: true
    
  # Organized paths
  paths:
    model_artifacts: "artifacts/"
    logs: "logs/"
    temp: "temp/"
    reports: "reports/"
    backups: "backups/"
    cache: "cache/"
    
  # NEW: Deployment settings
  deployment:
    container_optimized: true
    auto_scaling_enabled: false
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"

# OPTIMIZATION: Enhanced Feature Flags
feature_flags:
  # Core features
  enable_advanced_validation: true
  enable_real_time_monitoring: true
  enable_batch_processing: true
  enable_model_explanation: true
  enable_confidence_intervals: true
  
  # Advanced features
  enable_a_b_testing: false
  enable_champion_challenger: false
  enable_auto_retraining: false
  enable_federated_learning: false
  
  # Experimental features
  enable_explainable_ai: true
  enable_fairness_testing: false
  enable_adversarial_testing: false
  enable_quantum_resistant: false
  
  # Performance features
  enable_gpu_acceleration: false
  enable_distributed_processing: false
  enable_edge_deployment: false

# NEW: Integration Configuration
integrations:
  # External APIs
  credit_bureau:
    enable: false
    provider: "CIBIL"
    timeout_seconds: 30
    
  payment_gateway:
    enable: false
    provider: "Razorpay"
    webhook_validation: true
    
  # Data sources
  data_sources:
    enable_real_time_feeds: false
    enable_batch_imports: true
    validation_required: true
    
  # Notifications
  notifications:
    email:
      enable: false
      smtp_server: ""
    sms:
      enable: false
      provider: ""
    slack:
      enable: false
      webhook_url: ""

# NEW: Disaster Recovery
disaster_recovery:
  enable: true
  
  # Backup strategy
  backup:
    frequency_hours: 24
    retention_days: 90
    compression: true
    encryption: true
    remote_backup: false
    
  # Recovery procedures
  recovery:
    rpo_hours: 24  # Recovery Point Objective
    rto_hours: 4   # Recovery Time Objective
    automated_recovery: false
    failover_region: ""
    
  # Health monitoring
  monitoring:
    enable_heartbeat: true
    heartbeat_interval_minutes: 5
    alert_on_failure: true
